on:
  workflow_dispatch:
  push:
    branches: ["main"]

name: Latex compile
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Check out repository
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            cv.tex
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Development Build"
      #     files: |
      #       cv.pdf
      - name: FTP site
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cluster028.hosting.ovh.net
          username: jeanloupez
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./public/
          server-dir: ./www/media/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            cv.tex
        #   git-ftp-args: --insecure --all