on:
  workflow_dispatch:
  push:
    branches: ["main"]

name: Latex compile

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Check out repository
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
            cv.tex
      - uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: cv.pdf
